---

language: node_js
node_js:
  - node

script:
  - make lint
  - make test-coverage

env:
  global:
    - secure: "LtZzwIh3EYGc+oHqypdg4lB4suts4kqBCzC8Ra2vWZ7oJCRdiVcMbQPnqDOo26YKPcIdVd+vC43vKDGXNPT68X7IzwS0BSCSUUvuLBGHEW84JfQYECjYcavqokOSwK0KbDbZoTburx7KaEt8Zu7/HX+Hb2mxTpdV1VbWpMxxOu9qYw2vRMLvgPF4Iiw9eIGjlcRc4T9vVQHQbI7Hi0Aw6YfCaMr5eupalhF4UdPc3D5UEFXoCa4uPmjKfOqopk8WQQ/cd2QpuOGVjTu5MsxAXCMD/OCkGL/OOXdbSieZsw00p188lNpd33bLYoX+7TN/j0VSkp1O5VAAo5hyqadMKsibxBZGURxqhduJKMOJBx2oigXYw1PhBJRp3iaXX8j4CJdHo4l+Yt6mdYcoZHJ8IW3M/1E4r/ty9z8jnf484IOYyeUwzhL8JpqIFBhBsh4KfC82zMzZx0vD2nci617vc9yWdZv4px62kfrJ3p2wEJzug5Ma3Q5EwEjWBusiOcUr/hgsJHA6meCjNh43N5BLrYTI9mafhMZk5/cjIzXBG0apqAgNMOj7ScZzqeKhXy7Y4iJzd+rTt6T+3JuNODz+e/xRIXM60hagJ79CleWohxZWpCq8V9lNjo/7K8nwRr9iKRO4ZlAVm4AXioe9yR41X9DNBIGA3g+WWzxstpRqUM0="
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
