name: workflow

on: push

jobs:
  test:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    name: test/node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: make install
      - run: make test

  coverage:
    needs: [test]
    name: test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: make install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TEST_REPORTER_ID }}

  checkCodeStyle:
    name: check codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: make install
      - run: make lint

  publish:
    needs: [test]
    name: publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 8.x
      - name: Check if version has been updated
        id: check-version
        uses: EndBug/version-check@master
      - if: steps.check-version.outputs.changed == 'true'
        run: 'echo "Version change! -> ${{ steps.check-version.outputs.type }}"'
      - if: steps.check.outputs.changed != 'true'
        run: 'echo "No version change :/"'
