name: workflow

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    name: test/node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: make install
      - run: make test
      - run: node -v

  coverage:
    needs: [test]
    name: test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: make install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TEST_REPORTER_ID }}
      - run: node -v

  checkCodeStyle:
    name: check codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: |
          make install
          make lint
      - run: node -v
